name: Cleanup

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *" # Every day at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.GHCR_PRUNE }}
          user: nileshmali
          container: rust-opencv-builder
          dry-run: true # Dry-run first, then change to `false`
          prune-untagged: true
          keep-last: 2
          prune-tags-regexes: |
            ^sha256-
